version: '3.8'

services:
  # The Database Service
  db:
    image: postgres:15-alpine
    container_name: mediclaim_db
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER}"]
      interval: 5s
      timeout: 5s
      retries: 5

  # The FastAPI API Service
  api:
    container_name: mediclaim_api
    build: .  # Build the image from the Dockerfile in the current directory
    command: ./entrypoint.sh
    volumes:
      - .:/app  # Mount the current directory into the container for live code changes
    ports:
      - "8000:8000"
    env_file:
      - .env  # Load environment variables from the .env file
    depends_on:
      db:
        condition: service_healthy # Wait for the db healthcheck to pass

volumes:
  postgres_data:
